feat: add styled-components
thiagopuntar/va-pra-cozinha pull request #1
Opened 2022-05-25 21:08 UTC by gdantasc

2022-05-27 16:26 UTC, oliveirabalsa requested changes
i'm not the reviewer please adjust this

2022-05-27 16:29 UTC, oliveirabalsa approved these changes

2022-05-27 16:40 UTC, thiagopuntar requested changes

2022-05-27 16:40 UTC, thiagopuntar commented on style/global.ts
> +* {
Please, add also *::before, *::after here.

2022-06-03 10:26 UTC, thiagopuntar approved these changes

2022-06-03 10:26 UTC, merged